;item ids

;weapons
Item_Cudgel = $00 ;こん棒
Item_Nagamaki = $01 ;長巻
Item_BufusCleaver = $02 ;ブフーの包丁
Item_Katana = $03 ;カタナ
Item_Dragonkiller = $04 ;ドラゴンキラー
Item_Mastersword = $05 ;どうたぬき
Item_KabrasBlade = $06 ;剛剣マンジカブラ
Item_SickleSlayer = $07 ;成仏の鎌
Item_Pickaxe = $08 ;つるはし
Item_HomingBlade = $09 ;必中の剣
Item_MinotaursAxe = $0A ;ミノタウロスの斧
Item_RazorWind = $0B ;妖刀かまいたち
Item_CyclopsKiller = $0C ;１ツ目殺し
Item_DrainBuster = $0D ;ドレインバスター
Item_Firebrand = $0E ;火迅風魔刀
Item_KabraReborn = $0F ;秘剣カブラステギ

;arrows
Item_WoodArrow = $10 ;木の矢
Item_IronArrow = $11 ;鉄の矢
Item_SilverArrow = $12 ;銀の矢
Item_13 = $13 ;unused slot
Item_14 = $14 ;unused slot
Item_15 = $15 ;unused slot

;shields
Item_HideShield = $16 ;皮甲の盾
Item_Bronzeward = $17 ;青銅甲の盾
Item_AntiPoisonShield = $18  ;unused item (jp name: 無どくの盾)
Item_WoodShield = $19 ;木甲の盾
Item_IronShield = $1A ;鉄甲の盾
Item_Dragonward = $1B ;ドラゴンシールド
Item_Windshield = $1C ;風魔の盾
Item_SpikedWard = $1D ;バトルカウンター
Item_ArmorWard = $1E  ;重装の盾
Item_EchoShield = $1F ;やまびこの盾
Item_EvasiveShield = $20 ;見切りの盾
Item_FancyShield = $21 ;見かけだおしの盾
Item_FragileShield = $22 ;使い捨ての盾
Item_BlastShield = $23 ;地雷ナバリの盾
Item_WalrusShield = $24 ;トドの盾
Item_Stormward = $25 ;ラセン風魔の盾
Item_26 = $26 ;unused slot
Item_27 = $27 ;unused slot

;herbs
Item_MedicinalHerb = $28 ;薬草
Item_RestorativeHerb = $29 ;弟切草
Item_HappinessHerb = $2A ;しあわせ草
Item_SightHerb = $2B ;めぐすり草
Item_DragonHerb = $2C ;ドラゴン草
Item_VictoryHerb = $2D ;無敵草
Item_AngelSeed = $2E ;天使の種
Item_RevivalHerb = $2F ;復活の草
Item_InvisibilityHerb = $30 ;消え去り草
Item_BitterHerb = $31 ;くねくね草
Item_MisfortuneHerb = $32 ;不幸の種
Item_IllLuckHerb = $33 ;超不幸の種
Item_KignyHerb = $34 ;キグニ族の種
Item_AmnesiaHerb = $35 ;物忘れの草
Item_36 = $36  ;unused
Item_LifeHerb = $37 ;命の草
Item_BigBellySeed = $38 ;胃拡張の種
Item_LittleBellySeed = $39 ;胃縮小の種
Item_TalkSeed = $3A ;話の種
Item_StrengthHerb = $3B ;ちからの草
Item_AntidoteHerb = $3C ;どく消し草
Item_PoisonHerb = $3D ;どく草
Item_ConfusionHerb = $3E ;混乱草
Item_SleepHerb = $3F ;睡眠草
Item_Weeds = $40 ;雑草
Item_41 = $41 ;unused slot
Item_42 = $42 ;unused slot
Item_43 = $43 ;unused slot
Item_44 = $44 ;unused slot
Item_45 = $45 ;unused slot
Item_46 = $46 ;unused slot
Item_47 = $47 ;unused slot
Item_48 = $48 ;unused slot
Item_49 = $49 ;unused slot
Item_4A = $4A ;unused slot
Item_4B = $4B ;unused slot
Item_4C = $4C ;unused slot
Item_4D = $4D ;unused slot
Item_4E = $4E ;unused slot
Item_4F = $4F ;unused slot
Item_50 = $50 ;unused slot
Item_51 = $51 ;unused slot
Item_52 = $52 ;unused slot
Item_53 = $53 ;unused slot
Item_54 = $54 ;unused slot
Item_55 = $55 ;unused slot

;scrolls
Item_BlessingScroll = $56  ;おはらいの巻物
Item_IdentityScroll = $57  ;識別の巻物
Item_LightScroll = $58  ;あかりの巻物
Item_BigpotScroll = $59  ;壺増大の巻物
Item_BlastwaveScroll = $5A  ;真空斬りの巻物
Item_SilenceScroll = $5B  ;くちなしの巻物
Item_5C = $5C  ;dummy entry
Item_TrapScroll = $5D  ;ワナの巻物
Item_NeedScroll = $5E  ;困った時の巻物
Item_HasteScroll = $5F  ;敵倍速の巻物
Item_SleepScroll = $60  ;バクスイの巻物
Item_PowerupScroll = $61  ;パワーアップの巻物
Item_62 = $62  ;dummy entry
Item_ExplosionScroll = $63  ;自爆の巻物
Item_GreatHallScroll = $64  ;大部屋の巻物
Item_MonsterHouseScroll = $65  ;モンスターハウスの巻物
Item_ConfusionScroll = $66  ;混乱の巻物
Item_RemovalScroll = $67  ;ジェノサイドの巻物
Item_BlankScroll = $68  ;白紙の巻物
Item_WanderingScroll = $69  ;迷子の巻物
Item_AirBlessScroll = $6A  ;天の恵みの巻物
Item_EarthBlessScroll = $6B  ;地の恵みの巻物
Item_PlatingScroll = $6C  ;メッキの巻物
Item_ExtractionScroll = $6D  ;吸い出しの巻物
Item_HandsFullScroll = $6E  ;拾えずの巻物
Item_6F = $6F  ;dummy entry
Item_70 = $70 ;unused slot
Item_71 = $71 ;unused slot
Item_72 = $72 ;unused slot
Item_73 = $73 ;unused slot
Item_74 = $74 ;unused slot
Item_75 = $75 ;unused slot
Item_76 = $76 ;unused slot
Item_77 = $77 ;unused slot
Item_78 = $78 ;unused slot
Item_79 = $79 ;unused slot
Item_7A = $7A ;unused slot
Item_7B = $7B ;unused slot

;staffs
Item_SlothStaff = $7C  ;封印の杖
Item_KnockbackStaff = $7D  ;ふきとばしの杖
Item_HappinessStaff = $7E  ;しあわせの杖
Item_MisfortuneStaff = $7F  ;不幸の杖
Item_DoppelgangerStaff = $80  ;身がわりの杖
Item_SwitchingStaff = $81  ;場所替えの杖
Item_BufusStaff = $82  ;ブフーの杖
Item_SkullStaff = $83  ;ガイコツまどうの杖
Item_ParalysisStaff = $84  ;かなしばりの杖
Item_PostponeStaff = $85  ;一時しのぎの杖
Item_PainSplitStaff = $86  ;痛み分けの杖
Item_87 = $87 ;unused slot
Item_88 = $88 ;unused slot
Item_89 = $89 ;unused slot
Item_8A = $8A ;unused slot
Item_8B = $8B ;unused slot
Item_8C = $8C ;unused slot
Item_8D = $8D ;unused slot
Item_8E = $8E ;unused slot
Item_8F = $8F ;unused slot
Item_90 = $90 ;unused slot
Item_91 = $91 ;unused slot
Item_92 = $92 ;unused slot

;armbands
Item_PassageArmband = $93  ;通過の腕輪
Item_DiscountArmband = $94  ;値切の腕輪
Item_TrapArmband = $95  ;ワナ師の腕輪
Item_Levelholder = $96  ;レベル固定の腕輪
Item_RecoveryArmband = $97  ;回復の腕輪
Item_RustlessArmband = $98  ;錆よけの腕輪
Item_CriticalArmband = $99  ;会心の腕輪
Item_RegretArmband = $9A  ;痛恨の腕輪
Item_BlessingArmband = $9B  ;呪いよけの腕輪
Item_PitchersArmband = $9C  ;遠投の腕輪
Item_HappyArmband = $9D  ;しあわせの腕輪
Item_LossArmband = $9E  ;垂れ流しの腕輪
Item_SightArmband = $9F  ;透視の腕輪
Item_CalmArmband = $A0  ;混乱よけの腕輪
Item_IdentityArmband = $A1  ;識別の腕輪
Item_A2 = $A2 ;unused slot
Item_A3 = $A3 ;unused slot
Item_A4 = $A4 ;unused slot
Item_A5 = $A5 ;unused slot
Item_A6 = $A6 ;unused slot
Item_A7 = $A7 ;unused slot
Item_A8 = $A8 ;unused slot
Item_A9 = $A9 ;unused slot
Item_AA = $AA ;unused slot
Item_AB = $AB ;unused slot
Item_AC = $AC ;unused slot
Item_AD = $AD ;unused slot

;onigiri
Item_Onigiri = $AE ;おにぎり
Item_BigOnigiri = $AF ;大きいおにぎり
Item_SpoiledOnigiri = $B0 ;くさったおにぎり
Item_HugeOnigiri = $B1 ;巨大なおにぎり
Item_SpecialOnigiri = $B2 ;特製おにぎり
Item_B3 = $B3 ;unused slot

;jars
Item_HoldingJar = $B4  ;保存の壺
Item_HidingJar = $B5  ;やりすごしの壺
Item_DivisionJar = $B6  ;分裂の壺
Item_StrengtheningJar = $B7  ;強化の壺
Item_IdentityJar = $B8  ;識別の壺
Item_ChiropracticJar = $B9
Item_StorehouseJar = $BA  ;倉庫の壺
Item_WeakeningJar = $BB  ;弱化の壺
Item_BC = $BC  ;dummy entry
Item_BottomlessJar = $BD  ;底抜けの壺
Item_MonsterJar = $BE  ;魔物のるつぼ
Item_ChangeJar = $BF  ;変化の壺
Item_MeldingJar = $C0  ;合成の壺
Item_WalrusJar = $C1  ;トドの壺
Item_GaibarasJar = $C2  ;ガイバラの壺
Item_PointlessJar = $C3  ;アホくさい壺
Item_UnbreakableJar = $C4  ;割れない壺
Item_VentingJar = $C5  ;うっぷんばらしの壺
Item_C6 = $C6 ;unused slot
Item_C7 = $C7 ;unused slot
Item_C8 = $C8 ;unused slot
Item_C9 = $C9 ;unused slot
Item_CA = $CA ;unused slot
Item_CB = $CB ;unused slot
Item_CC = $CC ;unused slot
Item_CD = $CD ;unused slot
Item_CE = $CE ;unused slot
Item_CF = $CF ;unused slot
Item_D0 = $D0 ;unused slot
Item_D1 = $D1 ;unused slot
Item_D2 = $D2 ;unused slot
Item_D3 = $D3 ;unused slot
Item_D4 = $D4 ;unused slot
Item_D5 = $D5 ;unused slot
Item_D6 = $D6 ;unused slot
Item_D7 = $D7 ;unused slot
Item_D8 = $D8 ;unused slot
Item_D9 = $D9 ;unused slot
Item_DA = $DA ;unused slot
Item_DB = $DB ;unused slot
Item_DC = $DC ;unused slot
Item_DD = $DD ;unused slot
Item_DE = $DE ;unused slot
Item_DF = $DF ;unused slot

;misc
Item_MonsterMeat = $E0 ;モンスターの肉
Item_GoldenFeather = $E1 ;黄金の羽根
Item_HappinessBox = $E2 ;しあわせの箱 torneko moment
Item_StrangeBox = $E3  ;奇妙な箱
Item_E4 = $E4  ;新規アイテム目的物
Item_Gitan = $E5 ;ギタン
Item_Null = $E6
Item_Nduba = $E7 ;ンドゥバ
