.include "rominfo.asm"
.include "hardware.asm"
.include "wram.asm"
.include "macros.asm"

.include "constants/text.asm"
.include "constants/npc.asm"
.include "constants/items.asm"
.include "constants/events.asm"
.include "constants/locations.asm"
.include "constants/objects.asm"
